### ISSUE TITLE
Cant get it to work on Docker mac

### ISSUE THREAD

**Issue by demha89** [Sleepingpirates/Invitarr#11]
Is there a way to get it to work on Mac? I've tried doing the docker installation but keep getting:
Unable to find image 'to:latest' locally

is there a way to fix?

**Comment by Sleepingpirates** [comment]
Hey @demha89 I have rewritten the code. It works without docker now. Just need to clone the this repo, put your discord token into bot.env. Install requirements and run with python. Please read the readme as all the instructions are available there.

**Comment by demha89** [comment]
Thank you!
