### ISSUE TITLE
Database file error

### ISSUE THREAD

**Issue by tinkerp** [Sleepingpirates/Invitarr#23]
Hello,

I was trying  to run the docker but i'm getting the following error:
![image](https://user-images.githubusercontent.com/7636183/126912620-887e7e26-03a8-4099-8964-7a5a44fb54f2.png)

Any ideas on what my be causing this issue?

**Comment by Sleepingpirates** [comment]
Fixed. I have removed the web gui and will be working on it. Please update to the lastest docker. Make sure to read the readme and wiki as they have been updated.
