### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Ladrek69** [Sleepingpirates/Invitarr#24]
Getting "Internal Server Error" after ive changed all the ports to 80

**Comment by Ladrek69** [comment]
bot not even doing DM's anymore

**Comment by iTzEthqnHD** [comment]
My users arent getting dm's either. No matter what I've tried, there is nothing happening. Commands kinda work.

**Comment by Ladrek69** [comment]
We both have this enabled https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents

**Comment by Sleepingpirates** [comment]
Fixed. I have removed the web gui and will be working on it. Please update to the lastest docker. Make sure to read the readme and wiki as they have been updated.
