### ISSUE TITLE
Users not getting DM on Discord

### ISSUE THREAD

**Issue by iTzEthqnHD** [Sleepingpirates/Invitarr#25]
My users arent getting DM's since the last update. I think it has something to do with Discord.

**Comment by Ladrek69** [comment]
me too

**Comment by Ladrek69** [comment]
We both have this enabled https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents

**Comment by Sleepingpirates** [comment]
Been trying to figure out why this is happening. I believe the Web-server (Flask) is interfering in someway because when I run the code without the webserver everything works fine.

**Comment by Sleepingpirates** [comment]
Fixed. I have removed the web gui and will be working on it. Please update to the lastest docker. Make sure to read the readme and wiki. Both have been updated as well.
