### ISSUE TITLE
Option - bot to handle 2 discord ranks

### ISSUE THREAD

**Issue by Ladrek69** [Sleepingpirates/Invitarr#27]
Would be awesome if t he bot could handle 2 discord ranks :)

**Comment by Sleepingpirates** [comment]
Do you mean multiple roles? I have added support for that.

**Comment by Ladrek69** [comment]
i only see option for 1 role :(

**Comment by Sleepingpirates** [comment]
You can add more than one using the command .roleadd @role 

For example to add the role "plex" 
.roleadd @plex 

Then if you want to add another role on top of that you can just run the command again with the other role and so on. 
.roleadd @randomrole

The bot will scan for role changes for both the roles then. 

As of right now maximum roles supported are 10. Also I will be adding a way to delete roles soon.

**Comment by Ladrek69** [comment]
oh awesome!!

**Comment by Ladrek69** [comment]
Thank you!
