### ISSUE TITLE
Discord server disappeared

### ISSUE THREAD

**Issue by BEisem** [Sleepingpirates/Invitarr#4]
What happened to your Discord server? It seems to have gone away...

**Comment by BEisem** [comment]
Anyone???

**Comment by coolcat97** [comment]
I'm also having this issue.. just noticed today.. did Pirate give up?

**Comment by coolcat97** [comment]
I pulled a copy of the source in-case it disappears.

**Comment by BEisem** [comment]
Hoping it's just that he is busy with finals, that's the last thing I heard on the Discord server. Good idea pulling the source code, hopefully if he gives up on it, someone else can take it over.

**Comment by coolcat97** [comment]
We could make a new server called Pirate's refugees

**Comment by BEisem** [comment]
He's back! https://discord.gg/dAKU7H

**Comment by Jorgen1040** [comment]
That invite expired, could you send a new invite?

**Comment by BEisem** [comment]
Here's a new one ... hopefully this won't expire: https://discord.gg/EnUBXmF

**Comment by Sleepingpirates** [comment]
Sorry Its been fixed

**Comment by qhello** [comment]
Invite is broken for me - any chance to fix it? 👍

**Comment by Sleepingpirates** [comment]
New discord server

https://discord.gg/mYbCgtDTrh
