### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by YaibaToKen** [Sleepingpirates/Invitarr#7]
Is there no way to make the bot read from a `*.cfg` file placed in the config directory mounted to the container?
Would make it a lot easier to modify things. Either that or allow first time setup to be done through the web interface, similar to Sonarr and Radarr.
If security concerns you with that, I'd say nobody should be exposing this service to the internet before having fully set it up.

I also can't seem to initiate a shell session into the container through Portainer. This only seems to be an issue with Invitarr.

**Comment by iTzEthqnHD** [comment]
> Is there no way to make the bot read from a `*.cfg` file placed in the config directory mounted to the container?
> Would make it a lot easier to modify things. Either that or allow first time setup to be done through the web interface, similar to Sonarr and Radarr.
> If security concerns you with that, I'd say nobody should be exposing this service to the internet before having fully set it up.
> 
> I also can't seem to initiate a shell session into the container through Portainer. This only seems to be an issue with Invitarr.

Is your instance DM'ing users? I am having issues with the bot not DM'ing users.

**Comment by YaibaToKen** [comment]
> > Is there no way to make the bot read from a `*.cfg` file placed in the config directory mounted to the container?
> > Would make it a lot easier to modify things. Either that or allow first time setup to be done through the web interface, similar to Sonarr and Radarr.
> > If security concerns you with that, I'd say nobody should be exposing this service to the internet before having fully set it up.
> > I also can't seem to initiate a shell session into the container through Portainer. This only seems to be an issue with Invitarr.
> 
> Is your instance DM'ing users? I am having issues with the bot not DM'ing users. If so, do you know how to fix it? This dev is not active to my knowledge.

Unfortunately I can't even do the first time configuration for the bot because I can't enter the container :/

**Comment by Sleepingpirates** [comment]
**How to fix bot not dm'ing users?** 

Enable Server Members Intent.
https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents

What are intents?
As of 2020-10-28, discord requires users declare what sort of information (i.e. events) they will require for their bot to operate.
This is done in the form of intents.
You can read more about intents here: https://discordpy.readthedocs.io/en/latest/intents.html

By default some intents such as members and presences are disabled as they are what is referred to as privileged.  Meaning you'll need to take some extra steps to support them.
Read up on privileged intents here: https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents

If you use on_member_* events in your code, without changes your bot will not function anymore!

**Comment by Sleepingpirates** [comment]
> Is there no way to make the bot read from a `*.cfg` file placed in the config directory mounted to the container?
> Would make it a lot easier to modify things. Either that or allow first time setup to be done through the web interface, similar to Sonarr and Radarr.
> If security concerns you with that, I'd say nobody should be exposing this service to the internet before having fully set it up.
> 
> I also can't seem to initiate a shell session into the container through Portainer. This only seems to be an issue with Invitarr.

Just update settings in the web ui after deploying the docker container.
Default login is admin admin
