### ISSUE TITLE
Bot dont work (DB and Adding)

### ISSUE THREAD

**Issue by JoKerIsCraZy** [Sleepingpirates/Invitarr#8]
Hey i tried to get the Bot to work but i seems like its broken or smth like that,

When i try to add someone to my db the db cant been open after adding it
![image](https://user-images.githubusercontent.com/47474211/100271574-fd1c0980-2f59-11eb-979c-cf6c4892ce4c.png)

And When i try to add someone to Plex i get this:
![image](https://user-images.githubusercontent.com/47474211/100271630-1755e780-2f5a-11eb-8dd3-e28e714daeb1.png)

I cant find the log file and idk what to do

**Comment by Sleepingpirates** [comment]
Fixed. Read new readme and wiki.
